footprint: [[0.07, 0.035], [-0.07, 0.035], 
            [-0.07, -0.13], [0.07, -0.13]] #机器人为矩形，设置机器的在坐标系内所占用的面积

obstacle_layer:
  enabled: true
  combination_method: 1
  track_unknown_space: true
  obstacle_range: 2.5
  raytrace_range: 3.0
  observation_sources: laser_scan_sensor #只关注激光雷达的数据
  laser_scan_sensor: {sensor_frame: laser, 
                    data_type: LaserScan, 
                    topic: scan, 
                    marking: true, clearing: true} #设定激光雷达的相关参数
 
inflation_layer:
  enabled: true
  cost_scaling_factor: 5.0
  inflation_radius: 0.16
 
static_layer:
  enabled: true

