footprint: [[0.035, -0.075], [-0.13, -0.075], [-0.13, 0.075],[0.035, 0.075]] #机器人为矩形，设置机器的在坐标系内所占用的面积

obstacle_layer:
  enabled: true
  combination_method: 1
  track_unknown_space: true
  obstacle_range: 3.5
  raytrace_range: 5.5
  observation_sources: laser_scan_sensor #只关注激光雷达的数据
  laser_scan_sensor: {sensor_frame: /base_laser, 
                    data_type: LaserScan, 
                    topic: /scan, 
                    marking: true, clearing: true,
                    inf_is_valid: true} #设定激光雷达的相关参数
  footprint_clearing_enabled: true
 
inflation_layer:
  enabled: true
  cost_scaling_factor: 3.0
  inflation_radius: 0.08
 
static_layer:
  enabled: true

