GlobalPlanner:
  allow_unknown: false
  default_tolerance: 0.3
  visualize_potential: false
  use_dijkstra: false
  use_quadratic: false
  use_grid_path: false
  old_navfn_behavior: false
  planner_frequency: 0.5
 
  lethal_cost: 253
  neutral_cost: 50
  cost_factor: 10.0
  publish_potential: false
  orientation_mode: 0
  orientation_window_size: 1