GlobalPlanner:
  allow_unknown: true
  default_tolerance: 0.1
  visualize_potential: false
  use_dijkstra: true
  use_quadratic: false
  use_grid_path: false
  old_navfn_behavior: false
 
  lethal_cost: 253
  neutral_cost: 30
  cost_factor: 2.0
  publish_potential: false
  orientation_mode: 0
  orientation_window_size: 1